### E2E TESTS
# E2E dev profile (other services have to be started locally)
# Using name "e2e-dev" because if using "dev" the properties of a dependency like 'order' would be used
server:
  port: 8088

spring:
  datasource:
    saga:
      url: jdbc:postgresql://localhost:5432/eventuate
      username: eventuate
      password: eventuate
      driver-class-name: org.postgresql.Driver
    inventory:
      url: jdbc:postgresql://localhost:5433/inventory
      username: inventory
      password: inventory
      driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27018/data

eventuatelocal:
  kafka:
    bootstrap:
      servers: localhost:9092
  zookeeper:
    connection:
      string: localhost:2181

t2:
  e2etest:
    orchestrator:
      url: http://localhost:8085/order

opentracing:
  jaeger:
    service-name: e2etest
    enabled: false
    udp-sender:
      host: localhost

logging:
  level:
    de.unistuttgart.t2: DEBUG
