info:
  app:
    version: '@project.version@'

spring:
  jpa:
    open-in-view: false
  datasource:
    saga:
      url: ${SPRING_DATASOURCE_SAGA_URL}
      username: ${SPRING_DATASOURCE_SAGA_USERNAME}
      password: ${SPRING_DATASOURCE_SAGA_PASSWORD}
      driver-class-name: ${SPRING_DATASOURCE_SAGA_DRIVER_CLASS_NAME:org.postgresql.Driver}
    inventory:
      url: ${SPRING_DATASOURCE_INVENTORY_URL}
      username: ${SPRING_DATASOURCE_INVENTORY_USERNAME}
      password: ${SPRING_DATASOURCE_INVENTORY_PASSWORD}
      driver-class-name: ${SPRING_DATASOURCE_INVENTORY_DRIVER_CLASS_NAME:org.postgresql.Driver}
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST}:27017/data

eventuatelocal:
  kafka:
    bootstrap:
      servers: ${EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS}
  zookeeper:
    connection:
      string: ${EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING}

opentracing:
  jaeger:
    service-name: e2etest
    enabled: ${T2_JAEGER_ENABLED}
    udp-sender:
      host: ${T2_JAEGER_HOST}

t2:
  e2etest:
    orchestrator:
      url: ${T2_ORCHESTRATOR_URL}
