info:
  app:
    version: '@project.version@'

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  data:
    mongodb:
      uri: ${SPRING_MONGO_URL}

eventuatelocal:
  kafka:
    bootstrap:
      servers: ${EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS}
  zookeeper:
    connection:
      string: ${EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING}

t2:
  e2etest:
    orchestrator:
      url: ${T2_ORCHESTRATOR_URL}