info:
  app:
    version: '@project.version@'

spring:
  jpa:
    open-in-view: false
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

eventuatelocal:
  kafka:
    bootstrap:
      servers: ${EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS}
  zookeeper:
    connection:
      string: ${EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING}

opentracing:
  jaeger:
    service-name: e2etest
    enabled: ${T2_JAEGER_ENABLED}
    udp-sender:
      host: ${T2_JAEGER_HOST}

t2:
  e2etest:
    orchestrator:
      url: ${T2_ORCHESTRATOR_URL}
