name: build and push docker image
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: set env
      run: |
         curl -o setenv.sh -- 'https://raw.githubusercontent.com/t2-project/kube/main/setenv.sh'
         vi setenv.sh -c ':%s/^export //' -c ':%s/\(.*\)#.*/\1/' -c ':%s/\s*$//g' -c ':wq' # Strip out 'export ' at the beginning, comments, and trailing whitespace
         cat setenv.sh >> $GITHUB_ENV
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: check out payment
      uses: actions/checkout@v2
      with:
        repository: t2-project/payment
        path: './payment'
    - name: check out order
      uses: actions/checkout@v2
      with:
        repository: t2-project/order
        path: './order'
    - name: check out inventory
      uses: actions/checkout@v2
      with:
        repository: t2-project/inventory
        path: './inventory'
    - name: check out common
      uses: actions/checkout@master
      with:
        repository: t2-project/common
        path: './common'
    - name: check out e2e-tests
      uses: actions/checkout@master
      with:
        path: './e2e-tests'

    - name: set up jdk
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
#   
    - name: build common
      run: cd common && ./mvnw clean install
#
    - name: build payment
      run: cd payment && ./mvnw clean install
#
    - name: build order
      run: cd order && ./mvnw clean install
#  
    - name: build inventory
      run: cd inventory && ./mvnw clean install
#
    - name: build e2etest
      run: cd e2e-tests && ./mvnw clean install
    - run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build and push (manual)
      run: |
        echo ${{ env.RELEASE_VERSION }}
        echo $RELEASE_VERSION
        cd e2e-tests
        docker build -t t2project/e2etest:${{ env.RELEASE_VERSION }} .
        docker push t2project/e2etest:${{ env.RELEASE_VERSION }}
